sonic:
  agent:
    # 替换为部署Agent机器的ipv4
    host: 192.168.1.1
    # 替换为Agent服务的端口，可以自行更改
    port: 7777
    # 替换为前端新增Agent生成的key
    key: 8112177e-9fb9-4f0b-9761-a61d58430ea2
  server:
    # 改成server的SONIC_SERVER_HOST
    host: 192.168.1.1
    # 改成server的SONIC_SERVER_PORT
    port: 3035

modules:
  android:
    # 是否开启安卓模块
    enable: true
    # 是否开启sonic-android-supply远程adb调试功能
    use-sas: true
  ios:
    # 如果不需要连接iOS设备，请将true改为false。开启的windows用户请确保本机已安装iTunes
    enable: true
    # 替换为你自己使用的wda的bundleId，如果没有.xctrunner后缀会自动补全，建议使用公司的开发者证书
    wda-bundle-id: com.sonic.WebDriverAgentRunner
  sgm:
    # 是否开启sonic-go-mitmproxy网络抓包功能
    enable: true